### PR TITLE
PSR-2 and Bugfixes

### PR DESCRIPTION
**Pull request by vertexvaar**
Hi jagandecapri,

i've made some changes to your class, mostly PSR-2 CGL stuff but some bugfixes, too.
I created a lot of small commits for better traceability of the changes i made, i hope you like and merge them.

### CODE REVIEW

**Comment by vertexvaar** [comment]
Ok, so the last commit is a bit tricky and should not be part of this PR stage, but i can't split that off.
But this should be the final change. The last commit always keeps the number of running tasks at $maxParallel. Otherwise, if there's a process taking minutes but all other finished it would be the only one running while 4 others (when $maxP. = 5) could run in parallel

**Comment by jagandecapri** [comment]
Hei Oliver,

Amazing man. I'll check it out ASAP. Thanks a lot.

**Comment by jagandecapri** [comment]
@vertexvaar This is really cool. I learned something from this PR today. Thanks a lot!!!

**Comment by vertexvaar** [comment]
Thanks for merging, no i can remove my fork ;)

**Pull request merged**
